---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Ensure perlbrew dependencies are installed on Debian.
  apt: "name={{ perlbrew_packages }} state={{ perlbrew_packages_state }}"
  become: yes
